#!/bin/bash
echo "Script Written by ziaa and can be access at ziaagikian@gmail.com"
/sbin/route add default gw 192.168.7.1
# Google server dns
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

#echo "Setting time using Pakistan ntp pool"
#echo "You can set your country address by visiting to http://www.pool.ntp.org/en/"
#/urs/bin/ntpdate -b -s -u pk.pool.ntp.org

